el7 and el8
Signed-off-by: Ashish Tiwari <ashishjaitiwari15112000@gmail.com>

diff --git a/.github/workflows/package-apisix-rpm-el7.yml b/.github/workflows/package-apisix-rpm-el7.yml
--- a/.github/workflows/package-apisix-rpm-el7.yml
+++ b/.github/workflows/package-apisix-rpm-el7.yml
@@ -37,53 +37,42 @@ jobs:
           sudo gem install --no-document fpm
           sudo apt-get install -y rpm
 
-      # - name: packaging APISIX(-remote) with remote code
-      #   run: |
-      #     make package type=rpm app=apisix version=master checkout=revolyssup/openssl3 image_base=centos image_tag=7 artifact=apisix-remote
+      - name: packaging APISIX(-remote) with remote code
+        run: |
+          make package type=rpm app=apisix version=master checkout=revolyssup/openssl3 image_base=centos image_tag=7 artifact=apisix-remote
 
       - name: packaging APISIX(-local) with local code
         run: |
           git clone https://github.com/revolyssup/apisix.git
           make package type=rpm app=apisix version=master checkout=revolyssup/openssl3 image_base=centos image_tag=7 local_code_path=./apisix artifact=apisix-local
 
-      - name: check output
-        run: ls $PWD/output
-
-      - name: install apisix rpm into container
+      - name: install apisix rpm into container for remote
         run: |
-          docker build -t apache/apisix:master-rpm-test --build-arg APISIX_VERSION=master -f test/apisix/Dockerfile.test.apisix.rpm.el7 .
+          docker build -t apache/apisix:master-rpm-test-remote --build-arg APISIX_VERSION=master -f test/apisix/Dockerfile.test.apisix.rpm.el7.remote .
 
-      # - name: enable apisix repository in container
-      #   run: 
-      #     docker exec centos7Instance bash -c "rpm --import https://repos.apiseven.com/KEYS"
-      #     docker exec centos7Instance bash -c "yum -y install https://repos.apiseven.com/packages/centos/apache-apisix-repo-1.0-1.noarch.rpm"
+      - name: check and ensure APISIX(-remote) is installed
+        run: |
+          docker run -d --name master-rpm-test-remote -v $(pwd)/test/apisix/config.yaml:/usr/local/apisix/conf/config.yaml -p 9180:9180 -p 9080:9080 -p 9443:9443 apache/apisix:master-rpm-test-remote
+          sleep 30
+          code=$(curl -k -i -m 20 -o /dev/null -s -w %{http_code} http://127.0.0.1:9180/apisix/admin/routes -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1')
+          if [ ! $code -eq 200 ]; then
+              echo "failed: failed to install Apache APISIX by rpm"
+              exit 1
+          fii
+          docker container stop  master-rpm-test-remote
+          docker container rm  master-rpm-test-remote
 
-      # - name: install APISIX(-remote) master by rpm in container
-      #   run: |
-      #     docker exec centos7Instance bash -c "yum -y localinstall /output/apisix-remote-master-0.el7.x86_64.rpm"
-      #     docker exec centos7Instance bash -c "apisix start"
-
-      # - name: check and ensure APISIX(-remote) master is installed
-      #   run: |
-      #     code=$(curl -k -i -m 20 -o /dev/null -s -w %{http_code} http://127.0.0.1:9180/apisix/admin/routes -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1')
-      #     if [ ! $code -eq 200 ]; then
-      #         echo "failed: failed to install Apache APISIX by rpm"
-      #         exit 1
-      #     fi
-
-      # - name: stop and uninstall APISIX(-remote) master
-      #   run: |
-      #     docker exec centos7Instance bash -c "pkill -f nginx"
-      #     docker exec centos7Instance bash -c "yum -y erase apisix-remote-master"
-
-      # - name: install APISIX(-local) by rpm in container
-      #   run: |
-      #     docker exec centos7Instance bash -c "yum -y localinstall /output/apisix-local-master-0.el7.x86_64.rpm"
-      #     docker exec centos7Instance bash -c "apisix start"
+      - name: install apisix rpm into container for local
+        run: |
+          docker build -t apache/apisix:master-rpm-test-local --build-arg APISIX_VERSION=master -f test/apisix/Dockerfile.test.apisix.rpm.el7.local .
 
       - name: check and ensure APISIX(-local) is installed
         run: |
-          docker run -d --name master-rpm-test -v $(pwd)/test/apisix/config.yaml:/usr/local/apisix/conf/config.yaml -p 9180:9180 -p 9080:9080 -p 9443:9443 apache/apisix:master-rpm-test 
+          docker run -d --name master-rpm-test-local -v $(pwd)/test/apisix/config.yaml:/usr/local/apisix/conf/config.yaml -p 9180:9180 -p 9080:9080 -p 9443:9443 apache/apisix:master-rpm-test-local
           sleep 30
-          docker logs master-rpm-test
+          code=$(curl -k -i -m 20 -o /dev/null -s -w %{http_code} http://127.0.0.1:9180/apisix/admin/routes -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1')
+          if [ ! $code -eq 200 ]; then
+              echo "failed: failed to install Apache APISIX by rpm"
+              exit 1
+          fii
 
