chore: build new dashboard ui into apisix rpm&deb package (#433)
Signed-off-by: Nic <qianyong@api7.ai>

diff --git a/.github/workflows/package-apisix-deb-ubuntu20.04.yml b/.github/workflows/package-apisix-deb-ubuntu20.04.yml
--- a/.github/workflows/package-apisix-deb-ubuntu20.04.yml
+++ b/.github/workflows/package-apisix-deb-ubuntu20.04.yml
@@ -27,6 +27,9 @@ jobs:
       - name: install dependencies
         run: |
           sudo apt-get install -y make
+          # install node.js and pnpm
+          sudo n lts
+          corepack enable pnpm
       
       - name: run apisix packaging
         run: |
@@ -60,6 +63,12 @@ jobs:
           if [[ $result_code -ne 200 ]]; then
               printf "result_code: %s\n" "$result_code"
               exit 125
+          fi
+
+          code=$(curl -k -i -m 20 -o /dev/null -s -w %{http_code} http://127.0.0.1:9180/ui/)
+          if [ ! $code -eq 200 ]; then
+              echo "failed: failed to access Apache APISIX UI"
+              exit 1
           fi
 
       - name: Publish Artifact
diff --git a/.github/workflows/package-apisix-rpm-ubi.yml b/.github/workflows/package-apisix-rpm-ubi.yml
--- a/.github/workflows/package-apisix-rpm-ubi.yml
+++ b/.github/workflows/package-apisix-rpm-ubi.yml
@@ -36,6 +36,9 @@ jobs:
           sudo apt-get install -y make ruby ruby-dev rubygems build-essential
           sudo gem install --no-document fpm
           sudo apt-get install -y rpm
+          # install node.js and pnpm
+          sudo n lts
+          corepack enable pnpm
 
       - name: packaging APISIX(-remote) with remote code
         run: |
@@ -46,6 +49,7 @@ jobs:
         run: |
           wget https://raw.githubusercontent.com/apache/apisix/${APISIX_VERSION}/.requirements && source .requirements
           git clone -b ${APISIX_VERSION} https://github.com/apache/apisix.git
+          ./build-apisix-dashboard.sh ./apisix
           make package type=rpm app=apisix version=master checkout=${APISIX_VERSION} runtime_version=${APISIX_RUNTIME} image_base=registry.access.redhat.com/ubi8/ubi image_tag=8.6 local_code_path=./apisix artifact=apisix-local
 
       - name: run ubi8 docker and mapping rpm into container
@@ -86,6 +90,12 @@ jobs:
           code=$(curl -k -i -m 20 -o /dev/null -s -w %{http_code} http://127.0.0.1:9180/apisix/admin/routes -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1')
           if [ ! $code -eq 200 ]; then
               echo "failed: failed to install Apache APISIX by rpm"
+              exit 1
+          fi
+
+          code=$(curl -k -i -m 20 -o /dev/null -s -w %{http_code} http://127.0.0.1:9180/ui/)
+          if [ ! $code -eq 200 ]; then
+              echo "failed: failed to access Apache APISIX UI"
               exit 1
           fi
 
