feat: Reduce CI files with combined test (#86)
Signed-off-by: imjoey <majunjie@apache.org>

diff --git a/.github/workflows/package-apisix-dashboard-el7.yml b/.github/workflows/package-apisix-dashboard-el7.yml
--- a/.github/workflows/package-apisix-dashboard-el7.yml
+++ b/.github/workflows/package-apisix-dashboard-el7.yml
@@ -34,21 +34,28 @@ jobs:
           sudo gem install --no-document fpm
           sudo apt-get install -y rpm
 
-      - name: run apisix-dashboard packaging test
+      - name: run apisix-dashboard(-remote) packaging test
         run: |
-          make package type=rpm app=dashboard version=${DASHBOARD_VERSION} checkout=release/${DASHBOARD_VERSION} image_base=centos image_tag=7
+          make package type=rpm app=dashboard version=${DASHBOARD_VERSION} checkout=release/${DASHBOARD_VERSION} \
+            image_base=centos image_tag=7 artifact=apisix-dashboard-remote
+
+      - name: run apisix-dashboard(-local) packaging test
+        run: |
+          git clone -b release/${DASHBOARD_VERSION} https://github.com/apache/apisix-dashboard.git
+          make package type=rpm app=dashboard version=${DASHBOARD_VERSION} checkout=${DASHBOARD_VERSION} \
+            image_base=centos image_tag=7 local_code_path=./apisix-dashboard artifact=apisix-dashboard-local
 
       - name: Run centos7 docker and mapping rpm into container
         run: |
           docker run -itd -v $PWD/output:/apisix-dashboard --name centos7Instance --net="host" docker.io/centos:7 /bin/bash
 
-      - name: Install rpm package
+      - name: Install apisix-dashboard(-remote) rpm package
         run: |
-          docker exec centos7Instance bash -c "yum install -y /apisix-dashboard/apisix-dashboard-${DASHBOARD_VERSION}-0.el7.x86_64.rpm"
+          docker exec centos7Instance bash -c "yum install -y /apisix-dashboard/apisix-dashboard-remote-${DASHBOARD_VERSION}-0.el7.x86_64.rpm"
           docker logs centos7Instance
           docker exec centos7Instance bash -c "cd /usr/local/apisix/dashboard/ && nohup ./manager-api &"
 
-      - name: Run test cases
+      - name: Run apisix-dashboard(-remote) test cases
         run: |
           code=$(curl -k -i -m 20 -o /dev/null -s -w %{http_code} http://127.0.0.1:9000)
           if [ ! $code -eq 200 ]; then
@@ -56,3 +63,21 @@ jobs:
               exit 1
           fi
 
+      - name: stop and uninstall apisix-dashboard(-remote)
+        run: |
+          docker exec centos7Instance bash -c "pkill -f manager-api"
+          docker exec centos7Instance bash -c "yum -y erase apisix-dashboard-remote-${DASHBOARD_VERSION}"
+
+      - name: Install apisix-dashboard(-local) rpm package
+        run: |
+          docker exec centos7Instance bash -c "yum install -y /apisix-dashboard/apisix-dashboard-local-${DASHBOARD_VERSION}-0.el7.x86_64.rpm"
+          docker logs centos7Instance
+          docker exec centos7Instance bash -c "cd /usr/local/apisix/dashboard/ && nohup ./manager-api &"
+
+      - name: Run apisix-dashboard(-local) test cases
+        run: |
+          code=$(curl -k -i -m 20 -o /dev/null -s -w %{http_code} http://127.0.0.1:9000)
+          if [ ! $code -eq 200 ]; then
+              echo "failed: failed to install Apache APISIX Dashboard by rpm"
+              exit 1
+          fi
