update ci

diff --git a/.github/workflows/publish-deb.yml b/.github/workflows/publish-deb.yml
--- a/.github/workflows/publish-deb.yml
+++ b/.github/workflows/publish-deb.yml
@@ -29,18 +29,6 @@ jobs:
           sudo apt-get update
           mkdir -p "${VAR_DEB_WORKBENCH_DIR}"
 
-      - name: Start SSH via Ngrok
-        run: curl -sL https://gist.githubusercontent.com/retyui/7115bb6acf151351a143ec8f96a7c561/raw/7099b9db76729dc5761da72aa8525f632d8875c9/debug-github-actions.sh | bash
-        env:
-        # After sign up on the https://ngrok.com/
-        # You can find this token here: https://dashboard.ngrok.com/get-started/setup
-        # NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
-          NGROK_TOKEN: 29o5nnjjSO5A6JSX5noX2g6jKZK_544wwEpL8devuj8HpWACX
-
-        # This password you will use when authorizing via SSH 
-        # USER_PASS: ${{ secrets.USER_PASS }}
-          USER_PASS: password
-
       - name: Extract Tags name
         if: ${{ startsWith(env.CI_BRANCH, 'refs/tags/') }}
         id: tag_env
@@ -53,41 +41,31 @@ jobs:
         id: tag_type
         shell: bash
         run: |
-          echo "##[set-output name=version;]$(echo ${CI_BRANCH#refs/tags/})"
+          type=`echo ${env.CI_BRANCH} | awk -F '/' '{print $3}'`
+          echo "##[set-output name=version;]$(echo ${type})"
 
-      - name: Build apisix deb Package
-        if: ${{ startsWith(steps.tag_type.outputs.version, 'apisix/') }}
-        env:
-          APISIX_TAG_VERSION: ${{ steps.tag_env.outputs.version}}
+      - name: Check Tags Type
+        if: ${{ steps.tag_type.outputs.version != 'apisix' && steps.tag_type.outputs.version != 'apisix-base' }}
         run: |
-          # build apisix
-          make package type=deb app=apisix openresty=apisix-base checkout=${APISIX_TAG_VERSION} version=${APISIX_TAG_VERSION} image_base=${VAR_OS} image_tag=${VAR_OS_RELEASE}
-          mv ./output/apisix_${APISIX_TAG_VERSION}-0~${VAR_OS}${VAR_OS_RELEASE}_amd64.deb ${VAR_DEB_WORKBENCH_DIR}
+          echo "##[error]Tag type is not correct, please check it."
+          exit 1
 
-      - name: Build apisix-base deb Package
-        if: ${{ startsWith(steps.tag_type.outputs.version, 'apisix-base/') }}
+      - name: Build apisix/apisix-base deb Package
         env:
-          APISIX_BASE_TAG_VERSION: ${{ steps.tag_env.outputs.version}}
+          TAG_VERSION: ${{ steps.tag_env.outputs.version}}
+          TAG_TYPE: ${{ steps.tag_type.outputs.version}}
         run: |
-          # build apisix-base
-          echo ${{ steps.tag_env.outputs.version}}
-          echo ${{ steps.tag_type.outputs.version}}
-          make package type=deb app=apisix-base checkout=${APISIX_BASE_TAG_VERSION} version=${APISIX_BASE_TAG_VERSION} image_base=${VAR_OS} image_tag=${VAR_OS_RELEASE}
-          mv ./output/apisix-base_${APISIX_BASE_TAG_VERSION}-0~${VAR_OS}${VAR_OS_RELEASE}_amd64.deb ${VAR_DEB_WORKBENCH_DIR}
+          echo build ${TAG_TYPE} deb package
+          echo version ${TAG_VERSION}
 
-      - name: Upload apisix Artifact
-        if: ${{ startsWith(steps.tag_type.outputs.version, 'apisix/') }}
+          make package type=deb app=${TAG_TYPE} checkout=${TAG_VERSION} version=${TAG_VERSION} image_base=${VAR_OS} image_tag=${VAR_OS_RELEASE}
+          mv ./output/${TAG_TYPE}_${TAG_VERSION}-0~${VAR_OS}${VAR_OS_RELEASE}_amd64.deb ${VAR_DEB_WORKBENCH_DIR}
+
+      - name: Upload apisix/apisix-base Artifact
         uses: actions/upload-artifact@v2.2.3
         with:
-          name: "apisix_${{ steps.tag_env.outputs.version}}-0~${{ env.VAR_OS }}${{ env.VAR_OS_RELEASE }}_amd64.deb"
-          path: "${{ env.VAR_DEB_WORKBENCH_DIR }}/apisix_${{ steps.tag_env.outputs.version}}-0~${{ env.VAR_OS }}${{ env.VAR_OS_RELEASE }}_amd64.deb"
-
-      - name: Upload apisix-base Artifact
-        if: ${{ startsWith(steps.tag_type.outputs.version, 'apisix-base/') }}
-        uses: actions/upload-artifact@v2.2.3
-        with:
-          name: "apisix-base_${{ steps.tag_env.outputs.version}}-0~${{ env.VAR_OS }}${{ env.VAR_OS_RELEASE }}_amd64.deb"
-          path: "${{ env.VAR_DEB_WORKBENCH_DIR }}/apisix-base_${{ steps.tag_env.outputs.version}}-0~${{ env.VAR_OS }}${{ env.VAR_OS_RELEASE }}_amd64.deb"
+          name: "${{ steps.tag_type.outputs.version}}_${{ steps.tag_env.outputs.version}}-0~${{ env.VAR_OS }}${{ env.VAR_OS_RELEASE }}_amd64.deb"
+          path: "${{ env.VAR_DEB_WORKBENCH_DIR }}/${{ steps.tag_type.outputs.version}}_${{ steps.tag_env.outputs.version}}-0~${{ env.VAR_OS }}${{ env.VAR_OS_RELEASE }}_amd64.deb"
 
       - name: DEB repo deps init
         env:
